language: node_js
node_js: 10
cache: yarn
install: yarn install
script:
- "$(yarn bin)/cypress run --record --key $cypressDashboard -c baseUrl=$baseURL --env
  CONTENTFUL_SPACE_ID=$contentfulSpaceId,CONTENTFUL_ENV=$contentfulEnv,CONTENTFUL_ACCESS_TOKEN=$contentfulToken"
notifications:
  slack:
    rooms:
      - secure: X7XZAJCqsmIkWaC+jEpAJijCecw1tgI1DulVu6clCn8HeyKdkzrxxUEmxzu4Dhj15aXui2Wl4SklO4ICW08kKqR+C46zwuReWfiDXoHoi02rT1dbcLqrpZUc7a/U13mxKqBnkQlSOi/A2q1Q5ET4zYtK753eiFcxz1BYCL7rSRuzrxBQjjdlxX4DhtAchNrgsdkZnhZrqmSQ3Ohw2Juevlt1mnJTmXsalziIQBdkYQVuFhQ2O/zUq7dRwuZCJeMYyKzNBnilQZvk5lNXpYQTaGQNkXknaikVxkcPfm9WCIJndhQG8ImbsllTY747R1K1JTVXZSQtV1sQMiMQ27Ji5NHN8nTwBvBmrE3wx0CfYe6BZXFJ0y+lmnodhF+/vzFLD+hG8REBM7Ute6Z7UTH7ZDqGfRDxKjeyI4UfGAmjZkufJC99SpDs9gA6+lCiqcdDI7BvdKU0auzE5+CC6ZFahkBbL5iYygoTFVzpx+7pPenzqirIUEss6Fv5V9DN+a/8jV1l7gp7+K2jZmy/67ldYybBl5vx2aCkf+A2RkT9yF4NzazJYNJ5jyKi4YZoEv/mKTt5snL7HQyvEjBWZo71CXf8iDpGxkY1pHou+fiyTt/6xnJVS1U2b5h9dz29MmY5FKjorbSWuOmAaELasdbwkcMWaOGXOaGUbY6UYU3h6II=
    on_success: always
    on_failure: always
    on_pull_requests: false
