language: node_js
node_js: 10
cache: yarn
install: yarn install
script:
- "$(yarn bin)/cypress run -c baseUrl=$baseURL --env
  CONTENTFUL_SPACE_ID=$contentfulSpaceId,CONTENTFUL_ENV=$contentfulEnv,CONTENTFUL_ACCESS_TOKEN=$contentfulToken,CRDS_BASE_URL=$crdsBaseUrl,CRDS_MEDIA_ENDPOINT=$mediaBaseUrl,ALGOLIA_INDEX=$algoliaIndex,ALGOLIA_APP_ID=$algoliaAppId,ALGOLIA_API_KEY=$algoliaApiKey"
notifications:
  slack: crdschurch:iZZLQf36DkUtiv0SqLhlOklj
