language: node_js
node_js:
  - '10'
dist: trusty #Needed to include Chrome
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn install
unitTests: &unitTest
  script: "yarn run test_headless"
integrationTests: &integrationTest
  script: "yarn run cypress run --record --key $cypressDashboard --parallel --group crds-search-parallel --browser chrome --env configFile=$configFile,CONTENTFUL_SPACE_ID=$contentfulSpaceId,CONTENTFUL_ACCESS_TOKEN=$contentfulToken,ALGOLIA_APP_ID=$algoliaAppId,ALGOLIA_API_KEY=$algoliaApiKey"
jobs:
  include:
    - stage: Unit Tests
      <<: *unitTest
  # run tests in parallel by including several jobs with same "stage" name
    - stage: Integraion Tests
      if: env(RUN_CYPRESS) = true
      <<: *integrationTest
    - stage: Integraion Tests
      if: env(RUN_CYPRESS) = true
      <<: *integrationTest
    - stage: Integraion Tests
      if: env(RUN_CYPRESS) = true
      <<: *integrationTest
notifications:
  slack:
    rooms:
      - crdschurch:iZZLQf36DkUtiv0SqLhlOklj
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
    on_pull_requests: false