language: node_js
node_js: 10
cache: yarn
install: yarn install
script:
- "$(yarn bin)/cypress run --record --key $cypressDashboard -c baseUrl=$baseURL --env
  CONTENTFUL_SPACE_ID=$contentfulSpaceId,CONTENTFUL_ENV=$contentfulEnv,CONTENTFUL_ACCESS_TOKEN=$contentfulToken"
notifications:
  slack:
    rooms:
      secure: WQqHUlEjqL9pS5u+ettWPuzAUm8oayuopUHAlvvbXPqtJDy6fWvVAR3R1KiC49dDSD30Bq5saOh1rTQ8T2uSIyRP4RZT6zzb5GSApj33kbkcWdOrrXM5hi6hjO2+iypd9TowcnKwcfU3kRC2H4Z6KeHSFR25+UEiBRIyfO3vWh152cJxhWzllGaTODWdNkd+vZKIZhfUx6kd76pfcDsJnxDNpfI/78HoiNaelvueq2DS/ZLrA6idesMa5c3hmmJTIAgCr7Ic7b57nfBMdck0mvn4v6K0Mo1MhCTgcvfuD/PnetStsaKc56K9TBjAXVyTVRFZMHLdk+fZKujB0MGi20djrSzZOqVofOCWa1wKR2Db6akovhIS7C03N3aOlXCk91FqKCBz0hsn/YhkwuxxLkxZTTiZLNlXX9Y0k8It/h8ylbH5AHWETJP1odnmF3Bun/lbKH5ZTYhHhDmve/b45U1UDmom7+TuSu/XLD8krzLAvkizqo6PSKvUsRmNapVyY2OwKnvy1K0LzoIyxM33SlYVf1GFbIk458ayJpOgD3AAd/PUWuaYctA053lVxGCthiIn+F2moHUJqb/tPLlS+KR7X9n0WY2FMUAVObWFJSt2fwO6tBrzjulU2xJbwR8ZQMnWhiLE5lnqnjwa8Rwm4zI7uk741tLMk38qPnFK4jI=
    on_success: always
    on_failure: always
    on_pull_requests: false
