language: node_js
node_js:
  - '10'
dist: trusty #Needed to include Chrome
addons:
  chrome: stable
  apt:
    packages:
      - libgconf-2-4
cache:
  yarn: true
  directories:
    - ~/.cache
install:
  - yarn install

# Unit Test stage
unitTests: &unitTest
  if: type = pull_request
  script: "yarn run test_headless"

# Integration Test stage
integrationTests: &integrationTest
  if: env(RUN_CYPRESS) = true
  script: "yarn run cypress run --record --key $cypressDashboard --parallel --group crds-search-parallel --browser chrome --env configFile=$configFile,VAULT_SECRET_ID=$VAULT_SECRET_ID,VAULT_ROLE_ID=$VAULT_ROLE_ID"

jobs:
  include:
    - stage: Unit Tests
      <<: *unitTest
    # run tests in parallel by including several jobs with same "stage" name
    - stage: Integraion Tests
      <<: *integrationTest
    - stage: Integraion Tests
      <<: *integrationTest
    - stage: Integraion Tests
      <<: *integrationTest

notifications:
  slack:
    rooms:
      - crdschurch:iZZLQf36DkUtiv0SqLhlOklj
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
    on_pull_requests: false