language: node_js
node_js:
  - '10'
cache:
  directories:
    - ~/.yarn
    - ~/.cache
install:
  - yarn install
defaults: &runCypress
  script:
  - "$(yarn bin)/cypress run --record --key $cypressDashboard --parallel --group crds-search-parallel --env useConfig=$config_file,CONTENTFUL_SPACE_ID=$contentfulSpaceId,CONTENTFUL_ACCESS_TOKEN=$contentfulToken,ALGOLIA_APP_ID=$algoliaAppId,ALGOLIA_API_KEY=$algoliaApiKey"
jobs:
  include:
  # run tests in parallel by including several jobs with same "stage" name
    - stage: test
      <<: *runCypress
    - stage: test
      <<: *runCypress
    - stage: test
      <<: *runCypress
    - stage: test
      <<: *runCypress
    - stage: test
      <<: *runCypress
notifications:
  slack:
    rooms:
      - crdschurch:iZZLQf36DkUtiv0SqLhlOklj
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{elapsed_time}"
    on_success: always
    on_failure: always
    on_pull_requests: false