# int build & anything that doesn't match below
[build]
  command = '''
  yarn run build --configuration=development &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = "yarn run build --configuration=preview"

[context.release]
  command = '''
  yarn run build --configuration=demo &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.master]
  command = "yarn run build --configuration=prod"
