# int build & anything that doesn't match below
[build]
  command = '''
  npm run build --configuration=development --base-href=/search/ &&
  npm run env:replace &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = '''
  npm run build --configuration=preview  &&
  npm run env:replace
  '''

[context.deploy-preview.environment]
  CRDS_ENV = "int"

[context.branch-deploy.environment]
  CRDS_ENV = "int"

[context.release]
  command = '''
  npm run build --configuration=demo --base-href=/search/ &&
  npm run env:replace &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.release.environment]
  CRDS_ENV = "demo"

[context.development.environment]
  CRDS_ENV = "int"

[context.master]
  command = '''
  npm run build --configuration=production --base-href=/search/ &&
  npm run env:replace
  '''

[context.master.environment]
  CRDS_ENV = "prod"

[context.production.environment]
  CRDS_ENV = "prod"
