# int build & anything that doesn't match below
[build]
  command = '''
  sed -i s/COMPONENT_PLACEHOLDER/$COMPONENT_CONFIG/g netlify.toml &&
  yarn run build --configuration=COMPONENT_PLACEHOLDERdevelopment &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = '''
  sed -i s/COMPONENT_PLACEHOLDER/$COMPONENT_CONFIG/g netlify.toml &&
  yarn run build --configuration=COMPONENT_PLACEHOLDERpreview
  '''

[context.release]
  command = '''
  sed -i s/COMPONENT_PLACEHOLDER/$COMPONENT_CONFIG/g netlify.toml &&
  yarn run build --configuration=COMPONENT_PLACEHOLDERdemo &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.master]
    command = '''
  sed -i s/COMPONENT_PLACEHOLDER/$COMPONENT_CONFIG/g netlify.toml &&
  yarn run build --configuration=COMPONENT_PLACEHOLDERproduction
  '''
