# int build & anything that doesn't match below
[build]
  command = '''
  npm run build --configuration=${COMPONENT_CONFIG}development &&
  npm run env:replace &&
  npm run package &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = '''
  npm run build --configuration=${COMPONENT_CONFIG}preview &&
  npm run env:replace &&
  npm run package
  '''

[context.deploy-preview.environment]
  CRDS_ENV = "int"

[context.branch-deploy.environment]
  CRDS_ENV = "int"

[context.release]
  command = '''
  npm run build --configuration=${COMPONENT_CONFIG}demo &&
  npm run env:replace &&
  npm run package &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.release.environment]
  CRDS_ENV = "demo"

[context.development.environment]
  CRDS_ENV = "int"

[context.master]
  command = '''
  npm run build --configuration=${COMPONENT_CONFIG}production &&
  npm run env:replace &&
  npm run package 
  '''

[context.master.environment]
  CRDS_ENV = "prod"

[context.production.environment]
  CRDS_ENV = "prod"
