# int build & anything that doesn't match below
[build]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}development &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}preview
  '''

[context.release]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}demo &&
  bash ./cypress/kickOffCypress.sh
  '''

[context.master]
    command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}production
  '''
