# int build & anything that doesn't match below
[build]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}development &&
  if [! -z "${COMPONENT_CONFIG}"]
  then
    yarn run package
  fi 
  && bash ./cypress/kickOffCypress.sh
  '''

[context.deploy-preview]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}preview &&
  if [! -z "${COMPONENT_CONFIG}"]
  then
    yarn run package
  fi
  '''

[context.release]
  command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}demo &&
  yarn run package &&
  if [! -z "${COMPONENT_CONFIG}"]
  then
    yarn run package
  fi 
  && bash ./cypress/kickOffCypress.sh
  '''

[context.master]
    command = '''
  yarn run build --configuration=${COMPONENT_CONFIG}production &&
  if [! -z "${COMPONENT_CONFIG}"]
  then
    yarn run package
  fi
  '''
